#**Introduction to Financial Python**
##NumPy and Basic Pandas

###**Introduction**

Now that we have introduced the fundamentals of Python, it's time to learn about NumPy and Pandas.

###**NumPy**

NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [1]:
import numpy as np

**Basic NumPy Arrays** 

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [2]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print (price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [3]:
#Mi ejemplo
score_list = [3.5, 4, 3.4, 4.3, 2.5, 5]
score_array = np.array(score_list)
print (score_array, type(score_array))

[3.5 4.  3.4 4.3 2.5 5. ] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. If we pass np.array() a list of lists, it will create a 2-dimensional array.

In [4]:
Ar = np.array([[1,3], [2,4]])
print (Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [5]:
#Mi ejemplo
Ar_2 = np.array([[1,2,3], [4,5,6]])
print (Ar_2, type(Ar_2))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:

In [6]:
print (Ar.shape)

(2, 2)


In [7]:
#Mi ejemplo
print (Ar_2.shape)

(2, 3)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:

In [8]:
print (Ar[0])
print (Ar[1])

[1 3]
[2 4]


In [9]:
#Mi ejemplo
print (Ar_2[0])
print (Ar_2[1])

[1 2 3]
[4 5 6]


If we want to access the matrix by column instead:

In [10]:
print ('First column:', Ar[:,0])
print ('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


In [11]:
#Mi ejemplo
print ('First column:', Ar_2[:,0])
print ('Second column:', Ar_2[:,1])
print ('Third column:', Ar_2[:,2])

First column: [1 4]
Second column: [2 5]
Third column: [3 6]


**Array Functions**

Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [12]:
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [13]:
#Mi ejemplo
np.log(score_array)

array([1.25276297, 1.38629436, 1.22377543, 1.45861502, 0.91629073,
       1.60943791])

Other functions return a single value:

In [14]:
print (np.mean(price_array))
print (np.std(price_array))
print (np.sum(price_array))
print (np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [15]:
#Mi ejemplo
print (np.mean(score_array))
print (np.std(score_array))
print (np.sum(score_array))
print (np.max(score_array))

3.783333333333333
0.7819136070493267
22.7
5.0


The functions above return the mean, standard deviation, total and maximum value of an array.

###**Pandas**

Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [16]:
import pandas as pd

**Series**

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [17]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print (s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [18]:
#Mi ejemplo
score = [3.5, 4, 3.4, 4.3, 2.5, 5]
s_2 = pd.Series(score)
print (s_2)

0    3.5
1    4.0
2    3.4
3    4.3
4    2.5
5    5.0
dtype: float64


We can customize the indices of a new Series:

In [19]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print (s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [20]:
#Mi ejemplo
s_2 = pd.Series(score, index = ['2016', '2017', '2018', '2019', '2020','2021'])
print (s_2)

2016    3.5
2017    4.0
2018    3.4
2019    4.3
2020    2.5
2021    5.0
dtype: float64


Or we can change the indices of an existing Series:

In [21]:
s.index = [6,5,4,3,2,1]
print (s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [22]:
#Mi ejemplo
s_2.index = [1,2,3,4,5,6]
print (s_2)

1    3.5
2    4.0
3    3.4
4    4.3
5    2.5
6    5.0
dtype: float64


Series is like a list since it can be sliced by index:

In [23]:
print (s[1:])
print (s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [24]:
#Mi ejemplo
print (s_2[1:])
print (s_2[:-2])

2    4.0
3    3.4
4    4.3
5    2.5
6    5.0
dtype: float64
1    3.5
2    4.0
3    3.4
4    4.3
dtype: float64


Series is also like a dictionary whose values can be set or fetched by index label:

In [25]:
print (s[4])
s[4] = 0
print (s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [26]:
#Mi ejemplo
print (s_2[4])
s_2[5] = 3
print (s_2)

4.3
1    3.5
2    4.0
3    3.4
4    4.3
5    3.0
6    5.0
dtype: float64


Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.

In [27]:
s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [28]:
#Mi ejemplo
s_2 = pd.Series(score, name = 'Race notes')
print (s_2)
print (s_2.name)

0    3.5
1    4.0
2    3.4
3    4.3
4    2.5
5    5.0
Name: Race notes, dtype: float64
Race notes


We can get the statistical summaries of a Series:

In [29]:
print (s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [30]:
#Mi ejemplo
print (s_2.describe())

count    6.000000
mean     3.783333
std      0.856543
min      2.500000
25%      3.425000
50%      3.750000
75%      4.225000
max      5.000000
Name: Race notes, dtype: float64


**Time Index**

Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:

In [31]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print (time_index)
s.index = time_index
print (s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [32]:
#Mi ejemplo
time_index_2 = pd.date_range('2020-02-07', periods = len(s), freq = 'M')
print (time_index_2)
s_2.index = time_index_2
print (s_2)

DatetimeIndex(['2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31',
               '2020-06-30', '2020-07-31'],
              dtype='datetime64[ns]', freq='M')
2020-02-29    3.5
2020-03-31    4.0
2020-04-30    3.4
2020-05-31    4.3
2020-06-30    2.5
2020-07-31    5.0
Freq: M, Name: Race notes, dtype: float64


Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:

In [33]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [34]:
#Mi ejemplo
s_2.index = [1,2,3,4,5,6]
print (s_2)
print (s_2[2])

1    3.5
2    4.0
3    3.4
4    4.3
5    2.5
6    5.0
Name: Race notes, dtype: float64
4.0


If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:

In [35]:
print (s.iloc[1])

145.83


In [36]:
#Mi ejemplo
print (s_2.iloc[3])

4.3


While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.

In [37]:
s.index = time_index
print (s['2017-01-03'])

143.68


In [38]:
#Mi ejemplo
s_2.index = time_index_2
print (s_2['2020-06-30'])

2.5


We can even access to a range of dates:

In [39]:
print (s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [40]:
#Mi ejemplo
print (s_2['2020-02-22':'2020-04-10'])

2020-02-29    3.5
2020-03-31    4.0
Freq: M, Name: Race notes, dtype: float64


Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:

In [41]:
print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [42]:
#Mi ejemplo
print (s_2[s_2 < np.mean(s_2)])
print (s_2[(s_2 > 3) & (s_2 < 4.5)])

2020-02-29    3.5
2020-04-30    3.4
2020-06-30    2.5
Name: Race notes, dtype: float64
2020-02-29    3.5
2020-03-31    4.0
2020-04-30    3.4
2020-05-31    4.3
Freq: M, Name: Race notes, dtype: float64


As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

###**Summary**

Here we have introduced NumPy and Pandas for scientific computing in Python. In the next chapter, we will dive into Pandas to learn resampling and manipulating Pandas DataFrame, which are commonly used in financial data analysis.